version: '3.7'

services:

  mysql:
    image: mysql:latest
    volumes:
      - ./mysql/:/var/lib/mysql/
      - ./docker/mysql:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 20982:80
    volumes:
      - ./:/app
